/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testproject;

import org.junit.Assert;
import org.junit.Test;

public class TestMyClass {
    @Test
    public void testIsEnabled() {
        MyClass classUnderTest = new MyClass();
        Assert.assertTrue("isEnabled should return 'true'", classUnderTest.isEnabled());
    }
}
